name: Francisco JY Lee

# Short bio or description (displayed in the header)
description: Master of Health Informatics student at the University of Toronto
avatar: /images/favicon-96x96.png
navigation:
  - name: About
    url: /about
  - name: Blog
    url: /
  - name: Tags
    url: /tags
  - name: Projects
    url: /projects
  - name: Theme
    url: https://github.com/AWEEKJ/kiko-now

footer-links:
  github: fleejy
  linkedin: jae-yong-francisco-lee-0b459013b


# Text under the icons in footer
footer-text: © 2018 Francisco JY Lee
url: http://fleejy.ca

# Site settings
title:
email:
author:
description:
url:

# Build settings
permalink: :title/
sass:
  sass_dir: css
