@@ -3,7 +3,7 @@
#

# Name of your site (displayed in the header)
name: Kiko Now
name: Francisco JY Lee

# Short bio or description (displayed in the header)
description: Master of Health Informatics student at the University of Toronto
avatar: /images/favicon-96x96.png
# and URL Link(e.g. 'Theme' tab below) tabs. If you don't need one, just delete
# it from the list(Delete '- name: ' and 'url: ', too!)
navigation:
  - name: Blog
    url: /
  - name: About
    url: /about
  - name: Archive
    url: /archive
  - name: Blog
    url: /
  - name: Tags
    url: /tags
  - name: Projects
    url: /projects
  - name: Theme
    url: https://github.com/AWEEKJ/kiko-now

footer-links:
  github: fleejy
  linkedin: jae-yong-francisco-lee-0b459013b


# Text under the icons in footer
footer-text: © 2018 Francisco JY Lee

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
@ -64,7 +64,7 @@ google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://fleejy.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)