---
title: fleejy.github.io
timezone: America/Toronto
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
name: Francisco JY Lee
author:

  name: Francisco JY Lee
  github: fleejy
  linkedin: jae-yong-francisco-lee-0b459013b
  email: jaeyongf.lee@mail.utoronto.ca

url: http://www.fleejy.ca
baseurl: ''
permalink: "/:year-:month-:day/:title/"
paginate: 5
paginate_path: "/page:num/"
markdown: kramdown
kramdown:
  imput: GFM
nav:
- name: About
  url: "/about"
- name: Blog
  url: "/blog"
- name: Tags
  url: "/tags"
- name: Projects
  url: "/projects"

sass:
  sass_dir: _sass
  style: :compressed
gems:
- jekyll-seo-tag
- jekyll-paginate
exclude:
- vendor